package bloomfilter

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"testing"
)

// These expected hashes and bit positions are generated by Java Guava, not by
// the Go hash implementation under test. Tests require no Java runtime.
type guavaMurmurFixtures struct {
	GuavaVersion       string              `json:"guava_version"`
	Seed               int                 `json:"seed"`
	ExpectedInsertions int                 `json:"expected_insertions"`
	ErrorRate          float64             `json:"error_rate"`
	Vectors            []guavaMurmurVector `json:"vectors"`
}

type guavaMurmurVector struct {
	Name     string          `json:"name"`
	InputHex string          `json:"input_hex"`
	HashHex  string          `json:"hash_hex"`
	Mitz32   guavaMurmurBits `json:"mitz32"`
	Mitz64   guavaMurmurBits `json:"mitz64"`
}

type guavaMurmurBits struct {
	HashFunctions byte     `json:"hash_functions"`
	WordCount     int      `json:"word_count"`
	SetBits       []uint64 `json:"set_bits"`
}

func loadGuavaMurmurFixtures(t *testing.T) guavaMurmurFixtures {
	t.Helper()
	data, err := os.ReadFile("guava_dump_files/murmur3_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures guavaMurmurFixtures
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatal(err)
	}
	if fixtures.Seed != 0 || fixtures.ExpectedInsertions != 500 || fixtures.ErrorRate != .01 || fixtures.GuavaVersion == "" {
		t.Fatal("unexpected Guava fixture configuration")
	}
	// Preserve the intended tail/block coverage when regenerating the corpus.
	names := make(map[string]bool)
	for _, vector := range fixtures.Vectors {
		if names[vector.Name] {
			t.Fatalf("duplicate fixture %q", vector.Name)
		}
		names[vector.Name] = true
	}
	for length := 0; length <= 64; length++ {
		if !names[fmt.Sprintf("pattern_%d", length)] {
			t.Fatalf("missing block/tail vector for length %d", length)
		}
	}
	for length := 1; length <= 32; length++ {
		if !names[fmt.Sprintf("ff_%d", length)] {
			t.Fatalf("missing unsigned-byte vector for length %d", length)
		}
	}
	return fixtures
}

func decodeMurmurFixtureHex(t *testing.T, value string) []byte {
	t.Helper()
	decoded, err := hex.DecodeString(value)
	if err != nil {
		t.Fatal(err)
	}
	return decoded
}

func TestMurmur3Sum128MatchesGuava(t *testing.T) {
	for _, vector := range loadGuavaMurmurFixtures(t).Vectors {
		t.Run(vector.Name, func(t *testing.T) {
			input := decodeMurmurFixtureHex(t, vector.InputHex)
			// Guava's HashCode bytes contain h1 then h2, both little-endian.
			expected := decodeMurmurFixtureHex(t, vector.HashHex)
			if len(expected) != 16 {
				t.Fatal("reference hash must contain 16 bytes")
			}
			want1, want2 := binary.LittleEndian.Uint64(expected[:8]), binary.LittleEndian.Uint64(expected[8:])
			if len(input) == 0 {
				if h1, h2 := murmur3Sum128(nil); h1 != want1 || h2 != want2 {
					t.Fatal("nil input differs from Guava's empty input")
				}
			}
			for offset := 0; offset < 16; offset++ {
				t.Run(fmt.Sprintf("offset_%d", offset), func(t *testing.T) {
					buffer := bytes.Repeat([]byte{0xa5}, len(input)+31)
					copy(buffer[offset:], input)
					before := append([]byte(nil), buffer...)
					// Cap the slice at its logical end; surrounding sentinel bytes
					// must not contribute to the hash or be modified by hashing.
					key := buffer[offset : offset+len(input) : offset+len(input)]
					h1, h2 := murmur3Sum128(key)
					if h1 != want1 || h2 != want2 {
						t.Fatalf("hash = %016x/%016x, want %016x/%016x", h1, h2, want1, want2)
					}
					if !bytes.Equal(buffer, before) {
						t.Fatal("hashing modified the key or surrounding bytes")
					}
				})
			}
		})
	}
}

func guavaMurmurFilterBytes(t *testing.T, ordinal byte, expected guavaMurmurBits) []byte {
	t.Helper()
	if expected.HashFunctions == 0 || expected.WordCount < 1 || expected.WordCount > 1024 || len(expected.SetBits) == 0 {
		t.Fatal("invalid reference filter metadata")
	}
	words := make([]uint64, expected.WordCount)
	for _, index := range expected.SetBits {
		if index >= uint64(expected.WordCount)*64 {
			t.Fatal("reference bit is outside the filter")
		}
		words[index/64] |= uint64(1) << (index % 64)
	}
	return serializedFilter(ordinal, expected.HashFunctions, words...)
}

func TestMurmur3FilterOperationsMatchGuava(t *testing.T) {
	fixtures := loadGuavaMurmurFixtures(t)
	typedKeys := map[string][]interface{}{
		"int32_min":       {int32(math.MinInt32), uint32(1 << 31), int(math.MinInt32)},
		"int32_max":       {int32(math.MaxInt32), uint32(math.MaxInt32), int(math.MaxInt32)},
		"int32_minus_one": {int32(-1), uint32(math.MaxUint32), int(-1)},
		"int64_min":       {int64(math.MinInt64), uint64(1 << 63)},
		"int64_max":       {int64(math.MaxInt64), uint64(math.MaxInt64)},
		"int64_minus_one": {int64(-1), uint64(math.MaxUint64)},
	}
	for _, vector := range fixtures.Vectors {
		t.Run(vector.Name, func(t *testing.T) {
			input := decodeMurmurFixtureHex(t, vector.InputHex)
			keys := []interface{}{input, string(input)}
			keys = append(keys, typedKeys[vector.Name]...)
			if len(input) == 0 {
				keys = append(keys, []byte(nil))
			}
			for _, strategy := range []struct {
				name     string
				value    Strategy
				ordinal  byte
				expected guavaMurmurBits
			}{
				{"mitz32", &Murur128Mitz32{}, 0, vector.Mitz32},
				{"mitz64", &Murur128Mitz64{}, 1, vector.Mitz64},
			} {
				t.Run(strategy.name, func(t *testing.T) {
					expected := guavaMurmurFilterBytes(t, strategy.ordinal, strategy.expected)
					for _, key := range keys {
						bf, err := NewBloomFilterWithStrategy(fixtures.ExpectedInsertions, fixtures.ErrorRate, strategy.value)
						if err != nil {
							t.Fatal(err)
						}
						if present, err := bf.MightContainChecked(key); present || err != nil {
							t.Fatalf("%T must be absent before insertion: %v", key, err)
						}
						if changed, err := bf.PutChecked(key); !changed || err != nil {
							t.Fatalf("first %T insertion failed: %v", key, err)
						}
						if bf.Put(key) {
							t.Fatal("repeated insertion changed bits")
						}
						if changed, err := bf.PutChecked(key); changed || err != nil {
							t.Fatal("repeated checked insertion changed bits or failed")
						}
						if !bytes.Equal(expected, bf.ToBytes()) {
							t.Fatalf("%T insertion differs from Guava's bit positions or serialization", key)
						}
						loaded, err := FromBytes(bf.ToBytes())
						if err != nil {
							t.Fatal(err)
						}
						if present, err := loaded.MightContainChecked(key); !present || err != nil || !loaded.MightContain(key) {
							t.Fatalf("%T was lost after serialization", key)
						}
						// Equivalent []byte and string keys must query the same hash.
						if !bf.MightContain(input) || !bf.MightContain(string(input)) {
							t.Fatal("equivalent byte encodings disagree")
						}
					}
					// Removing any Guava-set bit must make the original key absent.
					// This catches lookups that accidentally skip a hash position.
					for _, index := range strategy.expected.SetBits {
						missingBit := append([]byte(nil), expected...)
						offset := serializedHeaderSize + int(index/64)*8
						word := binary.BigEndian.Uint64(missingBit[offset : offset+8])
						binary.BigEndian.PutUint64(missingBit[offset:offset+8], word & ^(uint64(1)<<(index%64)))
						bf, err := FromBytes(missingBit)
						if err != nil {
							t.Fatal(err)
						}
						if present, err := bf.MightContainChecked(input); present || err != nil || bf.MightContain(input) {
							t.Fatalf("lookup ignored missing bit %d: %v", index, err)
						}
					}
				})
			}
		})
	}
}
